### EnergyETL

In [46]:
# import dependencies
import pandas as pd
from sqlalchemy import create_engine

In [47]:
# read csv file
file_path = "Resources/us_potential_energy.csv"

# create the data frame 
energy_df = pd.read_csv(file_path)
energy_df.head()

,States,urbanUtilityScalePV_GWh,urbanUtilityScalePV_GW,urbanUtilityScalePV_km2,ruralUtilityScalePV_GWh,ruralUtilityScalePV_GW,ruralUtilityScalePV_km2,rooftopPV_GWh,rooftopPV_GW,CSP_GWh,...,biopowerGaseous_GWh,biopowerGaseous_GW,biopowerGaseous_Tonnes-CH4,geothermalHydrothermal_GWh,geothermalHydrothermal_GW,EGSGeothermal_GWh,EGSGeothermal_GW,hydropower_GWh,hydropower_GW,hydropower_countOfSites
0,Alabama,35850,20,426,3706838,2114,44058,15475.0,12,0,...,1533,0,326186,0,0,535489.0,67.0,4102,0,2435
1,Alaska,166,0,2,8282976,9005,187608,NaN,1,0,...,61,0,13156,15437,1,NaN,NaN,23675,5,3053
2,Arizona,121305,52,1096,11867693,5147,107230,22736.0,14,12544333,...,837,0,178188,8329,1,1239147.0,157.0,1303,0,1958
3,Arkansas,28960,15,332,4986388,2747,57239,8484.0,6,0,...,1063,0,226178,0,0,628621.0,79.0,6093,1,3268
4,California,246008,111,2320,8855917,4010,83549,106411.0,75,8490916,...,15510,1,3300211,130921,16,1344179.0,170.0,30023,6,9692

In [48]:
# select the columns
energy_df = energy_df[["States", "urbanUtilityScalePV_GWh","ruralUtilityScalePV_GWh","rooftopPV_GWh", "CSP_GWh","onshoreWind_GWh","offshoreWind_GWh", "biopowerSolid_GWh", "biopowerGaseous_GWh", "geothermalHydrothermal_GWh", "EGSGeothermal_GWh", "hydropower_GWh"]]
                     
# display the new dataframe
energy_df.head()

,States,urbanUtilityScalePV_GWh,ruralUtilityScalePV_GWh,rooftopPV_GWh,CSP_GWh,onshoreWind_GWh,offshoreWind_GWh,biopowerSolid_GWh,biopowerGaseous_GWh,geothermalHydrothermal_GWh,EGSGeothermal_GWh,hydropower_GWh
0,Alabama,35850,3706838,15475.0,0,283,0.0,11193,1533,0,535489.0,4102
1,Alaska,166,8282976,NaN,0,1373433,NaN,513,61,15437,NaN,23675
2,Arizona,121305,11867693,22736.0,12544333,26036,NaN,1087,837,8329,1239147.0,1303
3,Arkansas,28960,4986388,8484.0,0,22892,NaN,14381,1063,0,628621.0,6093
4,California,246008,8855917,106411.0,8490916,89862,2662579.0,12408,15510,130921,1344179.0,30023

In [49]:
# rename the columns
energy_df.columns=["States", "Urban_Solar", "Rural_Solar", "Rooftop_Solar", "CSP_Solar", "Onshore_Wind", "Offshore_Wind", "Biopower_Solid", "Biopower_Gaseous", "Geothermal_Hydrothermal", "EGS_Geothermal", "Hydropower"]
energy_df.head()

,States,Urban_Solar,Rural_Solar,Rooftop_Solar,CSP_Solar,Onshore_Wind,Offshore_Wind,Biopower_Solid,Biopower_Gaseous,Geothermal_Hydrothermal,EGS_Geothermal,Hydropower
0,Alabama,35850,3706838,15475.0,0,283,0.0,11193,1533,0,535489.0,4102
1,Alaska,166,8282976,NaN,0,1373433,NaN,513,61,15437,NaN,23675
2,Arizona,121305,11867693,22736.0,12544333,26036,NaN,1087,837,8329,1239147.0,1303
3,Arkansas,28960,4986388,8484.0,0,22892,NaN,14381,1063,0,628621.0,6093
4,California,246008,8855917,106411.0,8490916,89862,2662579.0,12408,15510,130921,1344179.0,30023

In [50]:
# change NaN values to 0
energy_df.fillna(0, inplace=True)
energy_df.head()

,States,Urban_Solar,Rural_Solar,Rooftop_Solar,CSP_Solar,Onshore_Wind,Offshore_Wind,Biopower_Solid,Biopower_Gaseous,Geothermal_Hydrothermal,EGS_Geothermal,Hydropower
0,Alabama,35850,3706838,15475.0,0,283,0.0,11193,1533,0,535489.0,4102
1,Alaska,166,8282976,0.0,0,1373433,0.0,513,61,15437,0.0,23675
2,Arizona,121305,11867693,22736.0,12544333,26036,0.0,1087,837,8329,1239147.0,1303
3,Arkansas,28960,4986388,8484.0,0,22892,0.0,14381,1063,0,628621.0,6093
4,California,246008,8855917,106411.0,8490916,89862,2662579.0,12408,15510,130921,1344179.0,30023

In [51]:
#output clean data frame to csv
potential_energy = "Resources/us_potential_energy(clean).csv"
energy_df.to_csv(potential_energy,index=False)

### Scrape Wikipedia for the US Census Population Estimates

In [45]:
# Store the Wikipedia URL
wiki_url = "https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States_by_population#cite_note-5"

# Use Pandas to scrape Wikipedia page for tables
wiki_tables = pd.read_html(wiki_url)

# Grab the first table
pop_est_df = wiki_tables[0]

# Grab the State & Population est. for 2018
pop_est_df = pop_est_df[['State', 'Estimate, July 1, 2019[5]']]

# Rename the columns
pop_est_df = pop_est_df.rename(columns={"Name": "State", "Estimate, July 1, 2019[5]": "Population"})

# Drop the Territories
pop_est_df = pop_est_df[0:52]

# Display the new DataFrame
pop_est_df.tail()

KeyError: "['Estimate, July 1, 2019[5]'] not in index"

In [36]:
# Read in Energy Consumption csv
tot_consum_csv = "Resources/total_energy_consumed.csv"

# Create the Consumption DataFrame
tot_consum_df = pd.read_csv(tot_consum_csv)

# Join Population and Total Energy Consumed DataFrames
tot_consum_df = tot_consum_df.merge(pop_est_df, on='State',how="inner")

#convert BTU's to Gigawatt hours
tot_energy_gwh = tot_consum_df['Total_Energy_Consumed'] * 1000000 * 0.00000000029 * tot_consum_df['Population']

#add Gigawatt hours to dataframe
tot_consum_df['Total_Energy_Consumed_Gwh'] = tot_energy_gwh
tot_consum_df = tot_consum_df[['Rank','State','Total_Energy_Consumed_Gwh']]
tot_consum_df.head()

ValueError: The column label 'State' is not unique.
For a multi-index, the label must be a tuple with elements corresponding to each level.

In [37]:
#connect to database
from config import sqldb_connect
engine = create_engine(sqldb_connect)

ModuleNotFoundError: No module named 'config'

In [38]:
#copy dataframes into database tables
pop_est_df.to_sql('state_population', con=engine, if_exists='replace')
energy_df.to_sql('energy_renewable', con=engine, if_exists='replace')
tot_consum_df.to_sql('energy_consumption', con=engine, if_exists='replace')

NameError: name 'engine' is not defined

In [39]:
#calcuate total renewable energy potential & add to master dataframe
renewable_master_df = energy_df.set_index('State')
renewable_master_sum = renewable_master_df.sum(axis=1)
renewable_master_df = pd.DataFrame(renewable_master_sum)
renewable_master_df = renewable_master_df.rename(columns={0:'Total Renewable'})
energy_master_df = tot_consum_df.merge(renewable_master_df, on='State')
energy_master_df.head()

KeyError: 'State'

In [40]:
#calcuate difference in renewable energy potential & consumption
#add to master dataframe
energy_diff = energy_master_df['Total Renewable'] - energy_master_df['Total_Energy_Consumed_Gwh']
energy_master_df['Energy Difference'] = energy_diff

energy_master_df.head()

NameError: name 'energy_master_df' is not defined

In [41]:
#output data frame to csv
energy_compare = "Resources/energy_totals_comparison.csv"
energy_master_df.to_csv(energy_compare,index=False)

#copy dataframe into database tables
energy_master_df.to_sql('energy_compare', con=engine, if_exists='replace')

NameError: name 'energy_master_df' is not defined

In [42]:
#Query database to find states with negative energy difference values
not_100_renew = engine.execute('select "State" from energy_compare where "Energy Difference" < 0').fetchall()
not_100_renew = [states[0] for states in not_100_renew]

#output query results
print('The following states do not have sufficient potential sources of renewable energy to meet their current energy consumption:')
for state in not_100_renew:
    print(state)

NameError: name 'engine' is not defined